# Generated by Django 5.1.6 on 2025-02-12 20:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom du plan")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Plans",
                "ordering": ["-date_modification"],
            },
        ),
        migrations.CreateModel(
            name="FormeGeometrique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_forme",
                    models.CharField(
                        choices=[
                            ("RECTANGLE", "Rectangle"),
                            ("CERCLE", "Cercle"),
                            ("DEMI_CERCLE", "Demi-cercle"),
                            ("LIGNE", "Ligne"),
                        ],
                        max_length=20,
                        verbose_name="Type de forme",
                    ),
                ),
                (
                    "geometrie",
                    django.contrib.gis.db.models.fields.GeometryField(
                        srid=4326, verbose_name="Géométrie"
                    ),
                ),
                (
                    "surface",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Surface (m²)"
                    ),
                ),
                (
                    "proprietes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Propriétés spécifiques"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formes",
                        to="plans.plan",
                        verbose_name="Plan associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forme géométrique",
                "verbose_name_plural": "Formes géométriques",
            },
        ),
        migrations.CreateModel(
            name="Connexion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometrie",
                    django.contrib.gis.db.models.fields.LineStringField(
                        srid=4326, verbose_name="Géométrie de la connexion"
                    ),
                ),
                (
                    "forme_destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connexions_entrantes",
                        to="plans.formegeometrique",
                        verbose_name="Forme destination",
                    ),
                ),
                (
                    "forme_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connexions_sortantes",
                        to="plans.formegeometrique",
                        verbose_name="Forme source",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connexions",
                        to="plans.plan",
                        verbose_name="Plan associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connexion",
                "verbose_name_plural": "Connexions",
            },
        ),
        migrations.CreateModel(
            name="TexteAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.CharField(max_length=500, verbose_name="Texte")),
                (
                    "position",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Position"
                    ),
                ),
                (
                    "rotation",
                    models.FloatField(default=0, verbose_name="Rotation (degrés)"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="plans.plan",
                        verbose_name="Plan associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Texte d'annotation",
                "verbose_name_plural": "Textes d'annotation",
            },
        ),
    ]
