# Generated by Django 5.1.6 on 2025-02-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formegeometrique",
            name="geometrie",
        ),
        migrations.RemoveField(
            model_name="formegeometrique",
            name="proprietes",
        ),
        migrations.RemoveField(
            model_name="formegeometrique",
            name="surface",
        ),
        migrations.AddField(
            model_name="formegeometrique",
            name="data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Données de la forme"
            ),
        ),
        migrations.AlterField(
            model_name="formegeometrique",
            name="type_forme",
            field=models.CharField(
                choices=[
                    ("RECTANGLE", "Rectangle"),
                    ("CERCLE", "Cercle"),
                    ("DEMI_CERCLE", "Demi-cercle"),
                    ("LIGNE", "Ligne"),
                    ("TEXTE", "Texte"),
                ],
                max_length=20,
                verbose_name="Type de forme",
            ),
        ),
    ]
