# Generated by Django 5.1.6 on 2025-02-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_remove_formegeometrique_geometrie_and_more"),
    ]

    operations = []
