# Generated by Django 5.1.6 on 2025-02-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_auto_20250220_1341"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stocke les préférences de dessin (type de trait, couleurs, etc.)",
                verbose_name="Préférences de dessin",
            ),
        ),
    ]
