# Generated by Django 5.1.6 on 2025-02-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0004_plan_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="elements",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Stocke les éléments du plan (formes, connexions, etc.)",
                verbose_name="Éléments du plan",
            ),
        ),
    ]
