# Generated by Django 5.1.6 on 2025-02-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0005_plan_elements"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="historique",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Stocke l'historique des modifications du plan",
                verbose_name="Historique des modifications",
            ),
        ),
    ]
