# Generated by Django 5.1.6 on 2025-02-22 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0006_plan_historique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="client",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "UTILISATEUR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plans_client",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Client assigné",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="concessionnaire",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "CONCESSIONNAIRE"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plans_concessionnaire",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Concessionnaire assigné",
            ),
        ),
    ]
