# Generated by Django 5.1.6 on 2025-03-09 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0007_plan_client_plan_concessionnaire"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="usine",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "USINE"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plans_usine",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usine assignée",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="client",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "AGRICULTEUR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plans_client",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agriculteur assigné",
            ),
        ),
    ]
