# Generated by Django 5.1.6 on 2025-03-09 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0008_plan_usine_alter_plan_client"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="client",
        ),
        migrations.AddField(
            model_name="plan",
            name="agriculteur",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "AGRICULTEUR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plans_agriculteur",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agriculteur assigné",
            ),
        ),
    ]
