# Generated by Django 5.1.6 on 2025-02-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="company_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nom de l'entreprise",
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="must_change_password",
            field=models.BooleanField(
                default=True, verbose_name="Doit changer le mot de passe"
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Numéro de téléphone"
            ),
        ),
    ]
