# Generated by Django 5.1.6 on 2025-02-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0002_utilisateur_company_name_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="utilisateur",
            constraint=models.UniqueConstraint(fields=("email",), name="unique_email"),
        ),
    ]
