# Generated by Django 5.1.6 on 2025-03-09 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_utilisateur_unique_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="usine",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "USINE"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="concessionnaires",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usine associée",
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="concessionnaire",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "CONCESSIONNAIRE"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agriculteurs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Concessionnaire associé",
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("USINE", "Usine"),
                    ("CONCESSIONNAIRE", "Concessionnaire"),
                    ("AGRICULTEUR", "Agriculteur"),
                ],
                default="AGRICULTEUR",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
    ]
